package br.com.rpgruler.main.view;

import br.com.rpgruler.main.MainScreen;
import br.com.rpgruler.main.view.generic.DefaultView;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.JButton;

/**
 * Simulador de dados
 *
 * @author kaciano
 */
public class DiceView extends DefaultView {

    /**
     * Creates new form DiceView
     *
     * @param screen <code>MainScreen</code> Tela principal
     */
    public DiceView(MainScreen screen) {
        super(screen);
        initialize();
    }

    /**
     * Metodo de inicialização
     */
    private void initialize() {
        setSize(320, 300);
        initComponents();
        for (Component c : jPDices.getComponents()) {
            if (c instanceof JButton) {
                JButton bt = (JButton) c;
                bt.addActionListener((ActionEvent e) -> {
                    simulateDice(bt);
                });
            }
        }
    }

    /**
     * Simula jogada de dados
     *
     * @param button JButton
     */
    private void simulateDice(JButton button) {
        switch (button.getName()) {
            case "D4":
                button.setText(throwDice(4));
                break;
            case "D6":
                button.setText(throwDice(6));
                break;
            case "D8":
                button.setText(throwDice(8));
                break;
            case "D10":
                button.setText(throwDice(10));
                break;
            case "D12":
                button.setText(throwDice(12));
                break;
            case "D20":
                button.setText(throwDice(20));
                break;
        }
    }

    /**
     * Metodo para simular a jogada de dados
     *
     * @param type <code>int</code> Tipo de dado
     * @return <code>String</code> Valor do dado
     */
    private String throwDice(int type) {
        return String.valueOf(new Random().nextInt(type) + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDices = new javax.swing.JPanel();
        D4 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        D12 = new javax.swing.JButton();
        D20 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Simulador de dados");
        setVisible(true);

        jPDices.setLayout(new java.awt.GridLayout(2, 3));

        D4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D4.setText("D4");
        D4.setName("D4"); // NOI18N
        jPDices.add(D4);

        D6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D6.setText("D6");
        D6.setName("D6"); // NOI18N
        jPDices.add(D6);

        D8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D8.setText("D8");
        D8.setName("D8"); // NOI18N
        jPDices.add(D8);

        D10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D10.setText("D10");
        D10.setName("D10"); // NOI18N
        jPDices.add(D10);

        D12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D12.setText("D12");
        D12.setName("D12"); // NOI18N
        jPDices.add(D12);

        D20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        D20.setText("D20");
        D20.setName("D20"); // NOI18N
        jPDices.add(D20);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/transition/switch.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPDices, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPDices, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Component c : jPDices.getComponents()) {
            if (c instanceof JButton) {
                JButton bt = (JButton) c;
                bt.setText(bt.getName());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D10;
    private javax.swing.JButton D12;
    private javax.swing.JButton D20;
    private javax.swing.JButton D4;
    private javax.swing.JButton D6;
    private javax.swing.JButton D8;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPDices;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
